-----------------------------------------------------------
-------------------- Magnitude Analysis -------------------
-----------------------------------------------------------

-- FIND TOTAL CUSTOMERS BY COUNTRY
SELECT 
	country,
	COUNT(customer_id) AS TotalCustomer
FROM [dbo].[dim_customers]
GROUP BY country
ORDER BY TotalCustomer DESC;

-- FIND TOTAL CUSTOMERS BY GENDER
SELECT 
	gender,
	COUNT(customer_id) AS TotalCustomer
FROM [dbo].[dim_customers]
GROUP BY gender
ORDER BY TotalCustomer DESC;

-- FIND TOTAL PRODUCT BY CATEGORY
SELECT 
	category,
	COUNT(product_id) AS TotalProduct
FROM [dbo].[dim_products]
GROUP BY category
ORDER BY TotalProduct DESC;

-- WHAT IS THE AVERAGE COST IN EACH CATEGORY
SELECT 
	category,
	AVG(cost) AS TotalCost
FROM [dbo].[dim_products]
GROUP BY category
ORDER BY TotalCost DESC;

-- TOTAL REVENEUE GENERATED FOR EACH CATEGORY
SELECT 
	category,
	SUM(quantity * price) AS TotalRevenue
FROM [dbo].[fact_sales] AS sls
LEFT JOIN [dbo].[dim_products] AS prd
	ON sls.product_key = prd.product_key
GROUP BY category
ORDER BY TotalRevenue DESC

-- TOTAL REVENUE GENERATED BY EACH CUSTOMER
SELECT 
	cust.customer_id,
	CONCAT(cust.first_name, ' ', cust.last_name),
	SUM(quantity * price) AS TotalRevenue
FROM [dbo].[fact_sales] AS sls 
LEFT JOIN [dbo].[dim_customers] AS cust
	ON cust.customer_key = sls.customer_key
GROUP BY cust.customer_id, cust.first_name, cust.last_name
ORDER BY TotalRevenue DESC

-- FIND THE DESTRIBUTION OF SOLD ITEMS ACROSS COUNTRIES
SELECT 
	country,
	SUM(quantity) AS TotalSoldItems
FROM [dbo].[fact_sales] AS sls
LEFT JOIN [dbo].[dim_customers] AS cust
	ON cust.customer_key = sls.customer_key
GROUP BY country
ORDER BY TotalSoldItems DESC
